---
- name: Actualiza todos los paquetes
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full

- name: Crea el directorio /home/{{ default_user }}/.local/share/tldr (hay un bug si no).
  file:
    path: "/home/{{ default_user }}/.local/share/tldr"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '755'
    modification_time: preserve
    access_time: preserve

- name: Instala algunos paquetes si no están
  become: true
  apt:
    name:
      - tree
      - adduser
      - sudo
      - python3
      - python3-passlib
      - tldr
      - rsync
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Crea los directorios /root/bin y /root/log
  become: true
  file:
    path: "/root/{{ item }}"
    state: directory
    mode: '755'
    owner: root
    group: root
  loop:
    - bin
    - log

- name: Copia update_reboot.sh a /root/bin
  become: true
  copy:
    src: update_reboot.sh
    dest: /root/bin/update_reboot.sh
    owner: root
    group: root
    mode: '750'

- name: Añade tarea al cron de root para actualizarse y reiniciarse a las 5:30h
  become: true
  cron:
    name: update_and_reboot
    user: root
    hour: 5
    minute: 30
    job: /root/bin/update_reboot.sh
